/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.swing.component.dashboard;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import model.Barang;
import model.Pengguna;
import model.Staff;

/**
 *
 * @author yulia
 */
public class BarangCard extends javax.swing.JPanel {

    private Pengguna pengguna = null;
    private Staff staff = null;

    //untuk barang
    public BarangCard(Barang barang) {
        initComponents();
        btnMakeStaff.setVisible(false);
        btnEdit.setVisible(true);
        btnDelete.setVisible(true);
        initLeftPic("default");
        initBtn();
        initAttributeAndLabel(barang.getNamaBarang(), barang.getKuantitas(), barang.getHarga());
    }

    public void initAttributeAndLabel(String namaBarang, int kuantitas, double harga) {
        lblNama.setText(namaBarang);
        lblKuantitas.setText(String.valueOf(kuantitas));
        lblHarga.setText(String.format("%.2f", harga));
        
    }

    public void addBtnMakeStaffActionListener(ActionListener event) {
        btnMakeStaff.addActionListener(event);
    }

    public void addBtnDeleteActionListener(ActionListener event) {
        btnDelete.addActionListener(event);
    }

    public void addBtnEditActionListener(ActionListener event) {
        btnEdit.addActionListener(event);
    }

    public void initLeftPic(String jenis) {
        Icon icon = null;
        if (jenis.equalsIgnoreCase("default")) {
            icon = new FlatSVGIcon("img/icon/barang-img.svg", 0.07f);
        }
        iconProfPic.setIcon(icon);
    }

    public void initBtn() {
        btnEdit.setText("");
        btnDelete.setText("");

        btnEdit.setIcon(new FlatSVGIcon("img/icon/edit.svg", 0.5f));
        btnDelete.setIcon(new FlatSVGIcon("img/icon/delete.svg", 0.5f));
        btnMakeStaff.setIcon(new FlatSVGIcon("img/icon/makestaff.svg", 0.5f));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerPanel = new view.swing.GradientPanelLeft();
        profilePanel = new javax.swing.JPanel();
        iconProfPic = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        lblNama = new javax.swing.JLabel();
        lblKuantitas = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        btnDelete = new view.swing.component.ButtonRound();
        btnEdit = new view.swing.component.ButtonRound();
        btnMakeStaff = new view.swing.component.ButtonRound();

        setForeground(new java.awt.Color(102, 153, 255));
        setOpaque(false);

        profilePanel.setBackground(new java.awt.Color(255, 255, 255));
        profilePanel.setOpaque(false);
        profilePanel.setPreferredSize(new java.awt.Dimension(80, 80));

        iconProfPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(iconProfPic)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(iconProfPic)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        infoPanel.setOpaque(false);
        infoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        lblNama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNama.setText("namaBarang");
        infoPanel.add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        lblKuantitas.setForeground(new java.awt.Color(255, 255, 255));
        lblKuantitas.setText("noTelp");
        infoPanel.add(lblKuantitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, -1, -1));

        lblHarga.setForeground(new java.awt.Color(255, 255, 255));
        lblHarga.setText("alamat");
        infoPanel.add(lblHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 50, -1, -1));

        btnDelete.setText("test");

        btnEdit.setText("test");

        btnMakeStaff.setText("Jadikan Staff");

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanelLayout.createSequentialGroup()
                        .addComponent(btnMakeStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(profilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMakeStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(containerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(containerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.swing.component.ButtonRound btnDelete;
    private view.swing.component.ButtonRound btnEdit;
    private view.swing.component.ButtonRound btnMakeStaff;
    private view.swing.GradientPanelLeft containerPanel;
    private javax.swing.JLabel iconProfPic;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblKuantitas;
    private javax.swing.JLabel lblNama;
    private javax.swing.JPanel profilePanel;
    // End of variables declaration//GEN-END:variables
}
